zc-sdk-version: "0.1"
name: OpenList
package: lazycat.community.app.openlist
version: 0.1.1
description: A new AList Fork to Anti Trust Crisis
homepage: https://github.com/OpenListTeam/OpenList
author: OpenListTeam
application:
  subdomain: openlist
  background_task: true
  public_path:
    - /
  routes:
    - /=http://openlist:5244/
services:
  openlist:
    image: registry.lazycat.cloud/czyt/openlistteam/openlist-git:5fbc31e7a7aff4f8
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - ALIST_ADMIN_PASSWORD=admin
      - TZ=UTC
    binds:
      - /lzcapp/var/data:/opt/openlist/data
ext_config:
  enable_document_access: true
  enable_media_access: true
