zc-sdk-version: "0.1"
name: DeepClaude
package: lazycat.community.app.openlist
version: 1.0.1
description: A new AList Fork to Anti Trust Crisis
homepage: https://github.com/OpenListTeam/OpenList
author: OpenListTeam
application:
    subdomain: openlist
    background_task: true
    public_path:
        - /
    routes:
        - /=http://openlist:5244/
services:
    openlist:
        image: ghcr.io/openlistteam/openlist:latest
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
            - TZ=UTC
        binds:
            - /lzcapp/var/data:/opt/openlist/data
ext_config:
    enable_document_access: true
    enable_media_access: true
