name: OpenList
min_os_version: 1.3.8
package: lazycat.community.app.openlist
version: 4.1.10
description: A new AList Fork to Anti Trust Crisis
homepage: https://github.com/OpenListTeam/OpenList
author: OpenListTeam
application:
    subdomain: openlist
    background_task: true
{{if .U.multi_instance}}
    multi_instance: true
{{end}}
    public_path:
        - /

    upstreams:
        - location: /
          backend: http://openlist:5244/

services:
    openlist:
        # openlistteam/openlist:v4.1.10-aio
        image: registry.lazycat.cloud/czyt/openlistteam/openlist:0b27f1c3a9223690
        user: root
        environment:
            - UMASK=022
            - OPENLIST_ADMIN_PASSWORD={{.U.openlistinitpass}}
            - TZ=UTC
        binds:
            - /lzcapp/var/data:/opt/openlist/data

ext_config:
    enable_document_access: true
    enable_media_access: true

locales:
    zh:
        name: "OpenList"
        description: "🗂一个支持多存储的文件列表程序，使用 Gin 和 Solidjs，基于 alist 项目 fork 开发"
    zh_CN:
        name: "OpenList"
        description: "🗂一个支持多存储的文件列表程序，使用 Gin 和 Solidjs，基于 alist 项目 fork 开发"
    en:
        name: "OpenList"
        description: "A new AList Fork to Anti Trust Crisis"
