name: OpenList
min_os_version: 1.3.8
package: lazycat.community.app.openlist
version: 4.1.2
description: A new AList Fork to Anti Trust Crisis
homepage: https://github.com/OpenListTeam/OpenList
author: OpenListTeam
application:
    subdomain: openlist
    background_task: true
{{if .U.multi_instance}}
    multi_instance: true
{{end}}
    public_path:
        - /

    upstreams:
        - location: /
          backend: http://openlist:5244/

services:
    openlist:
        # openlistteam/openlist:v4.1.2-aio
        image: registry.lazycat.cloud/czyt/openlistteam/openlist:38fd8f08fb88860a
        user: root
        environment:
            - UMASK=022
            - OPENLIST_ADMIN_PASSWORD={{.U.openlistinitpass}}
            - TZ=UTC
        binds:
            - /lzcapp/var/data:/opt/openlist/data

ext_config:
    enable_document_access: true
    enable_media_access: true

locales:
    zh:
        name: "OpenList"
        description: "反垄断危机的新AList分支"
    zh_CN:
        name: "OpenList"
        description: "反垄断危机的新AList分支"
    en:
        name: "OpenList"
        description: "A new AList Fork to Anti Trust Crisis"
