package: lazycat.community.app.openlist
version: 4.2.4
name: OpenList
description: A new AList Fork to Anti Trust Crisis
min_os_version: 1.5.0
homepage: https://github.com/OpenListTeam/OpenList
author: OpenListTeam
locales:
  zh:
    name: "OpenList"
    description: "\U0001F5C2一个支持多存储的文件列表程序，使用 Gin 和 Solidjs，基于 alist 项目 fork 开发"
  zh_CN:
    name: "OpenList"
    description: "\U0001F5C2一个支持多存储的文件列表程序，使用 Gin 和 Solidjs，基于 alist 项目 fork 开发"
  en:
    name: "OpenList"
    description: "A new AList Fork to Anti Trust Crisis"
